### PR TITLE
Add Exceptions

### PR DESCRIPTION
**Pull request by chellmann**
Added Exceptions to Code

### CODE REVIEW

**Comment by chellmann** [comment]
also added support for return packages

**Comment by BernhardK91** [comment]
@chellmann Thank you very much for your contribution. Just one question: What does the following code is for? I did not find anything in the documentation.
`'parcels' => [
    'returns' => false
],`

**EDIT:**
Just found in the documentation:
> Defines if parcel is a return parcel. The return parcel must always be next in order to the corresponding outbound parcel. Default value is false.

Can you explain to me what a "return parcel" is?

**Comment by chellmann** [comment]
@BernhardK91 a parcel with a return label can be dropped off in any DPD-Shop or handed to the driver. It can be used to send goods back to their sender. Please note, that the Sender and Receiver Adress are automatical swapped.

**Comment by BernhardK91** [comment]
@chellmann Thx! So the default is already "false" but in this case I thinks it is good to set that value manually. So Pull request will be merged. Thank you very much! :+1:

**Pull request merged**
